export const tools = [
  { id: 1, label: "Html5", path: "/icons/htmll.png" },
  { id: 2, label: "Css3", path: "/icons/css3.png" },
  { id: 3, label: "JavaScript", path: "/icons/js.png" },
  { id: 4, label: "ReactJs", path: "/icons/react.png" },
  { id: 5, label: "NextJs", path: "/icons/Next.png" },
  { id: 6, label: "TypeScript", path: "/icons/typescript.png" },
  { id: 7, label: "TailwindCss", path: "/icons/tailwind.jfif" },
  { id: 8, label: "Sass", path: "/icons/sass.jfif" },
  { id: 9, label: "Firebase", path: "/icons/firebase.jfif" },
  { id: 10, label: "MongoDB", path: "/icons/mongodb.png" },
  { id: 11, label: "Node", path: "/icons/node.png" },
  { id: 12, label: "Redux", path: "/icons/redux.png" },
  { id: 13, label: "API", path: "/icons/api.png" },
  { id: 14, label: "Jest", path: "/icons/jest.png" },
  { id: 15, label: "Git", path: "/icons/git.png" },
  { id: 16, label: "GitHub", path: "/icons/github.png" },
  { id: 17, label: "Vs code", path: "/icons/vs code.png" },
];
